#Display an image of Beep and ask input from user
print ("  #######")
print ("  #  .  #")
print ("  # --- #     Hello, I`m Beep, please choose my eyes so i can see you!")
print ("  #######")
print ("  ()%%%()")
print (" () %%% ()")
print ("()  %%%  ()")
print ("    %%%")
print ("    \_/")
eye= input()
print ("  #######")
print ("  # " + eye + "." + eye + " #")
print ("  # --- #   Thank you human! Now what is your name?")
print ("  #######")
print ("  ()%%%()")
print (" () %%% ()")
print ("()  %%%  ()")
print ("    %%%")
print ("    \_/")
name= input()
print ("  #######")
print ("  # " + eye + "." + eye + " #")
print ("  #\___/#   Nice to meet you " + name + "!")
print ("  #######")
print ("  ()%%%() ()")
print (" () %%% ()")
print ("()  %%%  ")
print ("    %%%")
print ("    \_/")